Update patch set 2
Patch Set 2:

BuildError: package rubygem-unf not in list for tag opstools7-fluentd-012-candidate

Needs to be fixed in CBS, we have now tooling for RDO leveraging rdoinfo, graffiti (tagging utility) + zuul to do that.

Patch-set: 2